sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ym19TXAteEDcG9m8k+eB1i3szQHaG4eV/k5cXYMjl4Fe/CZCvqG6sDXpOjeH5dKEf7HbgA4kL9ZYQRVYXwbG9rDnNW0dqR2mh9XW6vFDJcJY0LFGrVU/pQ5vj2wnzG0AeG8sQkuMNOqDVeN0gicFjzKOLhb1icUzQsnk3Fd3uKkUEeiUd2X/JASdvhYlx2rCFQjhYxAgYNtDh5/s6i7FY0Wm8Ochbeq/0NlFQ2PDxInYTFpEwS2MKPxXAhnQRLhxUfPWgEPFAGq+YDw8/M/bH3XlEjntK/IPktuFTfYMTpRVOESA+qvL3Njnm5+NOJE3jUQoJL700Rs0UBVdR7a0b0kgIdamruHxAhv0PIxDw8lFk11V6JbPRARXrvuOhNavkdWfKuOAV+t7/055Qysax3UhlCmQfVghuru1+kA1XsKfpTCNOANUrUR4g8A/BHnpzYGWYUUsJ0vk3zJbVfGAILtVpggQVrG+k47dwaBHdlCnB9gRaPtujuhMXoYC/5T76FlaoyClr25Ree8+dFxrm6LYIGTxhW15aNhbctxjqO9px7qOOhAEJCuEdsMFx4zV/hEpW6RClX6Ph2XA8Dn+A8saXTSRPgssJpvJATRWQ8PfCZ3Z6wSf0Ro/dz1gbTKISyG3sEta5xZq+vHygXEjAWpcxF48/3xhpIkgNkUqGhk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Elsie-Venner_2696
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy